export const FETCH_SEARCH_TITLE_REQUEST = 'FETCH_SEARCH_TITLE_REQUEST';
export const FETCH_SEARCH_TITLE_SUCCESS = 'FETCH_SEARCH_TITLE_SUCCESS';
export const FETCH_SEARCH_TITLE_ERROR = 'FETCH_SEARCH_TITLE_ERROR';
export const ADD_TO_WATCHED = 'ADD_TO_WATCHED';
export const ADD_TO_WATCHLIST = 'ADD_TO_WATCHLIST';
